// I / Ясно: a colorful world, continuous lessons, optional original audio.
let clarityFirstRender=true;
const clarityTitles=['Дроби','Числа','Фигуры'];
const clarityLessons=[[
 {title:'Это половина',text:'Круг разделён на две равные части. Одна часть закрашена. Это половина круга.',idea:'Половина — одна из двух равных частей.',a:1,b:2,factors:[1,2],labels:['2 части','4 части'],start:1,instruction:'Раздели круг на 4 части.'},
 {title:'Частей больше. Круг тот же.',text:'Теперь закрашены две части из четырёх. Вместе они всё ещё составляют половину круга.',idea:'Одна вторая и две четвёртых — равные дроби.',a:1,b:2,factors:[1,2,3],labels:['2 части','4 части','6 частей'],start:2,instruction:'Попробуй разделить круг ещё раз.'},
 {title:'Делаем запись короче',text:'Закрашены две части из четырёх. Уберём лишние линии. Получится одна часть из двух.',idea:'Две четвёртых можно записать как одну вторую.',a:1,b:2,factors:[2,1],labels:['4 части','2 части'],start:2,instruction:'Нажми «2 части». Что изменилось?'}
],[
 {title:'Из чего состоит число?',text:'В числе 470 есть 4 сотни и 7 десятков. Четыре сотни — это 40 десятков. Всего 47 десятков.',idea:'470 = 400 + 70'},
 {title:'Сначала умножаем',text:'Посчитаем 6 + 3 × 4. Сначала 3 × 4 = 12. Потом 6 + 12 = 18.',idea:'Сначала умножение. Потом сложение.'},
 {title:'Сначала считаем в скобках',text:'Посчитаем (6 + 3) × 4. Сначала 6 + 3 = 9. Потом 9 × 4 = 36.',idea:'Скобки показывают, с чего начать.'}
],[
 {title:'Считаем длину сторон',text:'У квадрата 4 равные стороны. Каждая — 4 см. Сложим их: 4 + 4 + 4 + 4 = 16 см.',idea:'Периметр — длина всех сторон вместе.'},
 {title:'Считаем клеточки',text:'В каждом ряду 5 клеточек. Всего 3 ряда. Получается 3 × 5 = 15 клеточек.',idea:'Площадь прямоугольника: длина × ширина.'},
 {title:'Площадь квадрата',text:'У квадрата 6 рядов по 6 клеточек. Получается 6 × 6 = 36.',idea:'Чтобы найти площадь квадрата, умножь сторону на себя.'}
]];
const clarityFactors={};
const clarityFractionQuestions=[
 {title:'Найди такую же половину',formula:['1','2'],answers:[['2','4'],['1','4'],['3','4']],correct:0,hint:'Половина из четырёх частей — две части.',explanation:'Верный ответ — 2/4. Две части из четырёх — это половина.'},
 {title:'Запиши дробь короче',formula:['2','4'],answers:[['1','4'],['1','2'],['2','3']],correct:1,hint:'Убери лишние линии. Вместо четырёх частей останутся две. Одна из них закрашена.',explanation:'Верный ответ — 1/2. Две четвёртых — та же половина.'},
 {title:'Найди ещё одну половину',formula:['1','2'],answers:[['2','6'],['3','6'],['4','6']],correct:1,hint:'Всего шесть частей. Половина от шести — три.',explanation:'Верный ответ — 3/6. Три части из шести — это половина.'}
];
function activeQuestion(){return ['i','j','l','m'].includes(variant)&&topicIndex===0?clarityFractionQuestions[question]:banks[topicIndex][question]}
function clarityDisc(n,d,id='main'){return discDiagram(n,d).replace(/(<svg[^>]*>)/,`$1<defs><pattern id="i-hatch-${id}" width="10" height="10" patternUnits="userSpaceOnUse"><rect width="10" height="10" fill="var(--d-lime)"/><path d="M-2 2L2 -2M0 10L10 0M8 12L12 8" stroke="var(--d-stroke)" stroke-width="1"/></pattern></defs>`).replaceAll('class="d-sector filled" style="',`class="d-sector filled" style="fill:url(#i-hatch-${id});`)}

function clarityIcon(name){const paths={home:'<path d="m3 11 9-8 9 8M5 10v11h5v-7h4v7h5V10"/>',book:'<path d="M12 5C8 2 4 3 2 4v16c3-2 7-2 10 0 3-2 7-2 10 0V4c-2-1-6-2-10 1Zm0 0v15"/>',chart:'<path d="M4 20V4M4 20h17M8 16v-4M13 16V8M18 16V5"/>',muted:'<path d="m11 4-6 5H2v6h3l6 5ZM16 9l6 6m0-6-6 6"/>',sound:'<path d="m11 4-6 5H2v6h3l6 5ZM15 8a6 6 0 0 1 0 8M18 4a11 11 0 0 1 0 16"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',back:'<path d="M20 12H4m6-6-6 6 6 6"/>',check:'<path d="m5 12 4 4L19 6"/>',plus:'<path d="M12 5v14M5 12h14"/>'};return `<svg class="i-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.book}</svg>`}
function clarityButton(text,action,secondary=false,icon='arrow'){return `<button class="i-button ${secondary?'i-secondary':''}" data-action="${action}">${icon==='back'?clarityIcon(icon):''}<span>${text}</span>${icon!=='back'?clarityIcon(icon):''}</button>`}
function clarityTools(){return `<details class="i-audio"><summary aria-label="Настроить звук"><span class="i-audio-icon">${clarityIcon(clarityAudio.music||clarityAudio.effects?'sound':'muted')}</span><span>Звук</span></summary><div class="i-audio-panel"><h2>Как звучит твой мир</h2><button data-action="clarity-effects" aria-pressed="${clarityAudio.effects}"><span>Звуки нажатий</span><span class="i-switch" aria-hidden="true"></span></button><button data-action="clarity-music" aria-pressed="${clarityAudio.music}"><span>Фоновая музыка</span><span class="i-switch" aria-hidden="true"></span></button><label for="i-volume">Громкость <output id="i-volume-value">${Math.round(clarityAudio.volume*100)}%</output></label><input type="range" id="i-volume" min="0" max="100" step="5" value="${Math.round(clarityAudio.volume*100)}"><p id="i-audio-status" role="status">Звук включается только по твоему желанию.</p></div></details>`}

function clarityNav(){return `<nav class="i-nav" aria-label="Главное меню">${[['today','Главная','home'],['learn','Темы','book'],['progress','Успехи','chart']].map(([id,label,icon])=>`<button data-go="${id}" ${screen===id?'aria-current="page"':''}>${clarityIcon(icon)}<span>${label}</span></button>`).join('')}</nav>`}
function clarityShell(content,animate){const focused=isLessonScreen(screen);return `<div class="i-shell ${focused?'i-focus':''}">${focused?`<header class="i-focus-header"><button class="i-exit" data-action="exit-lesson">${clarityIcon('back')}<span>Выйти</span></button><img class="i-focus-brand" src="assets/knight-${dark?'dark':'light'}.jpg" alt="Espada"><div class="i-step-status"><strong>${screen==='lesson'?clarityTitles[topicIndex]:`Задание ${question+1} из 3`}</strong>${screen==='practice'?`<div class="i-step-track" role="progressbar" aria-label="Номер задания" aria-valuemin="0" aria-valuemax="3" aria-valuenow="${question+1}">${Array.from({length:3},(_,i)=>`<span class="${i<=question?'done':''}"></span>`).join('')}</div>`:'<span class="i-reading-label">Читаем и пробуем</span>'}</div><div class="i-header-tools">${clarityThemeButton()}${clarityTools()}</div></header>`:`<header class="i-header"><button class="i-brand" data-go="today" aria-label="Espada — главная"><img src="assets/knight-${dark?'dark':'light'}.jpg" alt=""> espada.</button><span class="i-subject">Маленькие открытия каждый день</span><div class="i-header-tools">${clarityThemeButton()}${clarityTools()}</div></header>`}<main class="i-main ${animate?'scene':''}" id="i-main">${content}</main>${focused?'':clarityNav()}<footer class="i-footer">Учебный пример · Espada</footer></div>`}

function clarityArt(i){return `<div class="i-world-art i-original-art"><span class="i-art-orbit" aria-hidden="true"></span><img src="assets/learning-hero.png" alt="" width="1280" height="1280" fetchpriority="high"><span class="i-art-caption">Большие открытия начинаются с любопытства.</span></div>`}

function clarityToday(){const i=topicIndex;return `<div class="i-greeting-row"><div class="i-greeting"><span class="i-eyebrow"><span aria-hidden="true">✦</span> Сегодня будет интересно</span><h1>Привет, Алексей!</h1><p>Мир большой. Давай разбираться вместе.</p></div><button class="i-xp-chip" data-go="progress" aria-label="Мой прогресс: ${clarityEarned.size*20} очков"><span aria-hidden="true">✦</span><strong>${clarityEarned.size*20} очков</strong>${clarityIcon('arrow')}</button></div><section class="i-assignment"><div class="i-assignment-copy"><span class="i-label">ТВОЁ СЛЕДУЮЩЕЕ ОТКРЫТИЕ</span><h2>${['Делим поровну.<br>Понимаем дроби.','Знакомые числа.<br>Новые открытия.','Фигуры вокруг.<br>Что внутри?'][i]}</h2><p>${['Как одна половинка превращается в две четвертинки? Давай посмотрим.','Почему порядок действий меняет ответ? Разберём на понятных примерах.','Узнаем, чем дорожка вокруг клумбы отличается от места для цветов.'][i]}</p><button class="i-button" ${readParts.size===3&&attempts.length===3?'data-action="clarity-repeat"':`data-topic="${i}"`}><span>${readParts.size===3&&attempts.length===3?'Повторить урок':readParts.size?'Вернуться к уроку':'Начать открытие'}</span>${clarityIcon('arrow')}</button><span class="i-meta">Читай и пробуй в своём темпе</span></div>${clarityArt(i)}</section><div class="i-home-progress">${clarityPointsCard()}<button class="i-map-preview" data-go="progress">${clarityMiniRadar()}<span><small>Карта знаний</small><strong>Посмотри, что уже получается</strong><em>Пример работы учителя · 6 навыков</em></span>${clarityIcon('arrow')}</button></div><div class="i-home-bottom"><div class="i-friendly-note"><span class="i-mini-sun" aria-hidden="true">✳</span><p>Можно не спешить.<br><strong>Учись в своём ритме.</strong></p></div><button class="i-other-topic" data-go="learn">${clarityIcon('book')}<span>Все темы</span>${clarityIcon('arrow')}</button></div>`}

function clarityCards(items){return `<ol class="i-route">${items.map(t=>{const progress=clarityTopicProgress(t.i),solved=[...clarityEarned].filter(key=>key.startsWith(t.i+':')).length,done=progress.attempts.length===3;return `<li class="i-route-stop ${t.i===topicIndex?'is-current':''} ${done?'is-done':''}"><div class="i-route-node" aria-hidden="true">${done?clarityIcon('check'):['½','123','△'][t.i]}</div><button class="i-route-card" data-topic="${t.i}" ${t.i===topicIndex?'aria-current="step"':''}><span class="i-route-copy"><span class="i-route-label">ТЕМА 0${t.i+1} · ${done?'ЗАДАНИЯ ПРОЙДЕНЫ':t.i===topicIndex?'ТЫ ЗДЕСЬ':'МОЖНО НАЧАТЬ'}</span><strong>${clarityTitles[t.i]}</strong><span class="i-route-description">${['Делим поровну. Собираем целое.','Считаем. Ищем порядок.','Изучаем стороны и клеточки.'][t.i]}</span><span class="i-route-steps"><span class="${progress.read.length===3?'done':''}">${clarityIcon(progress.read.length===3?'check':'book')} Урок</span><span class="${done?'done':''}">${clarityIcon(done?'check':'chart')} ${progress.attempts.length}/3 задания</span></span><span class="i-route-cta">${done?'Повторить':progress.read.length||progress.attempts.length?'Продолжить':'Начать'} ${clarityIcon('arrow')}<small>${solved*20} / 60 очков</small></span></span><img src="assets/${topics[t.i].image}" alt="" width="120" height="120"></button></li>`}).join('')}</ol>`}

function clarityLearn(){return `<div class="i-route-intro"><div><span class="i-eyebrow">МАТЕМАТИКА</span><h1>Твой маршрут</h1><p class="i-lead">Выбирай тему. Читай, пробуй и собирай очки.</p></div><span class="i-route-total">${clarityIcon('check')} ${clarityCompletedTopics()} из 3 тем пройдено</span></div><div class="i-search"><label for="search">Найти тему</label><input id="search" type="search" placeholder="Например, дроби" autocomplete="off"></div><div id="topics" class="i-topics">${topicCards()}</div><p class="i-route-footnote">Все темы открыты — можно идти в своём порядке.</p><label class="sr-only" for="grade">Класс</label><select id="grade" hidden><option value="all">Все классы</option><option value="5">5 класс</option><option value="6">6 класс</option></select>`}

function clarityExplorer(index){const c=clarityLessons[0][index],factor=clarityFactors[index]??c.start;return `<section class="i-experiment" data-experiment="${index}" aria-labelledby="i-experiment-title-${index}"><span class="i-play-label">Твоя очередь</span><h3 id="i-experiment-title-${index}">${c.instruction}</h3><div class="i-experiment-body"><div class="i-disc">${clarityDisc(c.a*factor,c.b*factor,'lesson-'+index)}</div><div class="i-experiment-controls"><div class="i-fraction-readout" aria-live="polite"><strong>${frac([c.a*factor,c.b*factor])}</strong><span>Закрашено ${c.a*factor} из ${c.b*factor} частей.</span></div><div class="i-split-buttons" role="group" aria-label="На сколько частей разделить круг">${c.factors.map((f,n)=>`<button data-clarity-factor="${f}" aria-pressed="${f===factor}">${c.labels[n]}</button>`).join('')}</div><p class="i-constant">Закрашенная половина не меняется.</p></div></div></section>`}

function clarityLesson(){const story=clarityStories[topicIndex];return `<article class="i-lesson"><header class="i-story-heading"><span class="i-eyebrow">Маленькое открытие / ${clarityTitles[topicIndex]}</span><h1>${story.title}</h1><p class="i-lead">${story.intro}</p><div class="i-story-banner" aria-hidden="true"><img src="${variant==='m'?sectionArtPath(['fractions','numbers','geometry'][topicIndex]):'assets/'+topics[topicIndex].image}" alt="" width="1200" height="800"><span>${story.caption}</span></div></header><nav class="i-contents" aria-label="В этом уроке">${story.sections.map((c,i)=>`<a href="#i-section-${i}"><span>${i+1}</span>${c.short}</a>`).join('')}</nav><div class="i-story-body">${story.sections.map((c,i)=>`<section class="i-story-section i-section-${i}" id="i-section-${i}" aria-labelledby="i-section-title-${i}"><div class="i-section-heading"><span class="i-section-number" aria-hidden="true">0${i+1}</span><h2 id="i-section-title-${i}" tabindex="-1">${c.title}</h2></div><div class="i-reading-copy">${c.paragraphs.map(p=>`<p>${p}</p>`).join('')}</div>${topicIndex===0?clarityExplorer(i):clarityOtherExplorer(i)}<aside class="i-idea">${clarityIcon('check')}<p>${clarityLessons[topicIndex][i].idea}</p></aside>${c.example?`<div class="i-worked-example"><span>А В ЖИЗНИ?</span><p>${c.example}</p></div>`:''}</section>`).join('')}</div><section class="i-story-finish"><span class="i-finish-spark" aria-hidden="true">✦</span><h2>А теперь — попробуем сами?</h2><p>Три задания по тому, что мы узнали.<br>К уроку всегда можно вернуться.</p>${clarityButton('Понятно, к заданиям','clarity-start-practice')}<span class="i-meta">Без таймера. В твоём темпе.</span></section></article>`}

function clarityPractice(){const q=activeQuestion();return `<section class="i-practice"><h1>${q.title}</h1><p class="i-lead">${checked?'Разберём ответ вместе.':'Нажми на один ответ.'}</p>${q.formula?`<div class="i-question-math" aria-label="${q.formula.join('/')} ${q.equation?'равно '+q.equation.join('/'):''}">${frac(q.formula)}${q.equation?' = '+frac(q.equation):''}</div>`:''}<div class="i-answers" role="group" aria-label="Варианты ответа">${q.answers.map((a,i)=>{const state=checked?(i===q.correct?'Правильный ответ':i===choice?'Твой ответ':''):i===choice?'Выбрано':'';return `<button class="i-answer ${choice===i?'selected':''} ${checked&&i===q.correct?'correct':''} ${checked&&choice===i&&i!==q.correct?'wrong':''}" data-choice="${i}" aria-pressed="${choice===i}" aria-label="${Array.isArray(a)?a.join('/'):a}${state?', '+state:''}" ${checked?'disabled':''}><span>${frac(a)}</span>${state?`<span class="i-answer-state">${i===q.correct&&checked?clarityIcon('check'):''}${state}</span>`:''}</button>`}).join('')}</div>${hinted&&!checked?`<aside class="i-help" role="status"><h2>Подсказка</h2><p>${q.hint}</p></aside>`:''}${checked?`<div class="i-feedback ${choice!==q.correct?'i-feedback-error':''}" role="status"><h2>${choice===q.correct?(hinted?'Верно! Подсказка помогла.':'Верно!'):'Давай разберёмся'}</h2><p>${q.explanation}</p></div>`:''}<div class="i-practice-actions">${checked?clarityButton(question===2?'Готово':'Дальше','question-next'):`<button class="i-button" data-action="check" ${choice===null?'disabled':''}><span>${choice===null?'Сначала выбери ответ':'Проверить'}</span>${clarityIcon('check')}</button>${hinted?'':clarityButton('Помоги мне','hint',true,'book')}`}</div></section>`}
function clarityRadarDetail(){const a=radarAreas[radarSelected];return `<h3>${a.label}</h3><p><strong>${a.current} из ${a.total}</strong> верно</p>${radarCompare?`<p>В прошлой работе — ${a.previous} из ${a.total}.</p>`:''}`}
function clarityRadar(){return `<section class="i-knowledge-card" aria-labelledby="i-knowledge-title"><div class="i-knowledge-heading"><div><span class="i-eyebrow">РАБОТЫ УЧИТЕЛЯ</span><h2 id="i-knowledge-title">Твоя карта знаний</h2><p>Каждый луч — один навык.</p></div><span class="i-report-date">2 октября</span></div><div class="i-report-content"><label class="i-compare"><input id="radar-compare" type="checkbox" ${radarCompare?'checked':''}>Сравнить с прошлой работой</label><div class="i-radar-columns"><div><div id="radar-drawing"></div><div class="i-chart-legend"><span><i></i>Сейчас</span><span class="d-previous-legend" ${radarCompare?'':'hidden'}><i></i>Раньше</span></div><p class="i-chart-scale">От центра к краю: от 0 до 100% верных ответов.</p></div><div><div class="d-radar-area-list i-radar-list" aria-label="Разделы работы">${radarAreas.map((a,i)=>`<button data-radar-area="${i}" aria-pressed="${radarSelected===i}">${variant==='m'?flatArt(['numbers','fractions','ratio','algebra','geometry','probability'][i],'m-radar-art'):`<span class="i-area-number">${i+1}</span>`}<span>${a.label}<strong>${a.current} из ${a.total} верно</strong></span></button>`).join('')}</div><div id="radar-detail" class="i-radar-detail" aria-live="polite">${clarityRadarDetail()}</div></div></div><p class="i-report-demo">Пример двух работ: 2 октября и 18 сентября. Учебные данные.</p></div></section>`}

function paintClarityRadar(){const target=document.getElementById('radar-drawing');if(!target)return;const width=target.getBoundingClientRect().width;if(!width)return;const r=Math.min(145,width*.31),height=r*2+110,cx=width/2,cy=height/2;
 const point=(i,v,extra=0)=>{const angle=i*Math.PI/3-Math.PI/2,dist=r*v/100+extra;return [cx+Math.cos(angle)*dist,cy+Math.sin(angle)*dist]};
 const points=v=>radarAreas.map((_,i)=>point(i,v).join(',')).join(' ');const polygon=period=>radarAreas.map((a,i)=>point(i,radarValue(a,period)).join(',')).join(' ');
 target.innerHTML=`<svg class="i-radar" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="Результаты по шести разделам. Подробные значения подписаны в списке рядом с диаграммой.">${[25,50,75,100].map(v=>`<polygon class="d-radar-grid" points="${points(v)}"/>`).join('')}${radarAreas.map((_,i)=>{const[x,y]=point(i,100),[tx,ty]=point(i,100,29);return `<line class="d-radar-grid" x1="${cx}" y1="${cy}" x2="${x}" y2="${y}"/><text x="${tx}" y="${ty+7}" text-anchor="middle">${i+1}</text>`}).join('')}<g class="d-radar-previous ${radarCompare?'':'is-hidden'}"><polygon points="${polygon('previous')}"/></g><polygon class="d-radar-current" points="${polygon('current')}"/>${radarAreas.map((a,i)=>{const[x,y]=point(i,radarValue(a,'current'));return `<circle class="i-radar-dot" cx="${x}" cy="${y}" r="${radarSelected===i?8:5}"/>`}).join('')}</svg>`;
}
function clarityProgress(){const own=attempts.filter(a=>a.correct&&!a.hinted).length,help=attempts.filter(a=>a.correct&&a.hinted).length,errors=attempts.filter(a=>!a.correct).length;return `<h1>${attempts.length===3?'Занятие готово!':'Мои успехи'}</h1><p class="i-lead">${attempts.length===3?'Ты попробовал все три задания.':'Здесь видно, что ты уже сделал.'}</p>${clarityPointsCard()}${clarityRadar()}<section class="i-progress-card"><div class="i-progress-title">${clarityIcon('book')}<h2>${clarityTitles[topicIndex]}</h2></div><p>${readParts.size===3?'Урок прочитан. Можно применять новое.':'К уроку можно вернуться в любой момент.'}</p>${attempts.length?`<ul class="i-results"><li><span>Верно без подсказки</span><strong>${own}</strong></li><li><span>Верно с подсказкой</span><strong>${help}</strong></li><li><span>Нужно разобрать</span><strong>${errors}</strong></li></ul><p>${errors?'Ошибаться можно. Посмотрим правило ещё раз.':help?'В следующий раз попробуй без подсказки.':'Хорошая работа. Продолжай в своём темпе.'}</p>`:'<p>Результаты заданий появятся здесь.</p>'}${clarityButton(attempts.length===3?(errors?'Повторить урок':'Выбрать новую тему'):attempts.length?'Продолжить задания':'К заданиям',attempts.length===3?(errors?'clarity-repeat':'learn'):'practice')}</section><p class="i-progress-note">Чтение и ответы считаются отдельно.</p>`}
function clarityPage(){return ({today:clarityToday,learn:clarityLearn,lesson:clarityLesson,practice:clarityPractice,progress:clarityProgress,profile:clarityToday})[screen]()}
function mountClarity(animate){document.body.classList.remove('i-large');claritySyncAudio();if(!['i','j','l','m'].includes(variant))return;const heading=app.querySelector('h1');heading?.setAttribute('tabindex','-1');if(animate&&!clarityFirstRender)heading?.focus({preventScroll:true});clarityFirstRender=false;clarityRefreshAudio();}
document.addEventListener('click',event=>{
 if(!['i','j','l','m'].includes(variant))return;
 const factorButton=event.target.closest('[data-clarity-factor]');
 if(factorButton){const block=factorButton.closest('[data-experiment]'),index=Number(block.dataset.experiment),factor=Number(factorButton.dataset.clarityFactor),c=clarityLessons[0][index];clarityFactors[index]=factor;block.querySelector('.i-disc').innerHTML=clarityDisc(c.a*factor,c.b*factor,'lesson-'+index);block.querySelector('.i-fraction-readout').innerHTML=`<strong>${frac([c.a*factor,c.b*factor])}</strong><span>Закрашено ${c.a*factor} из ${c.b*factor} частей.</span>`;block.querySelectorAll('[data-clarity-factor]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.clarityFactor)===factor));return}
 const action=event.target.closest('[data-action]')?.dataset.action;
 if(action==='clarity-theme'){dark=!dark;render(false);if(parent!==window)parent.postMessage({type:'espada-lab-theme',dark},location.protocol==='file:'?'*':location.origin);return}
 if(action==='clarity-repeat'){part=0;readParts.clear();resetPractice();for(const key of Object.keys(clarityFactors))delete clarityFactors[key];go('lesson')}
 if(action==='clarity-start-practice'){[0,1,2].forEach(i=>readParts.add(i));if(attempts.length===3)resetPractice();go('practice')}
 if(action==='clarity-effects'||action==='clarity-music')clarityToggleAudio(action==='clarity-effects'?'effects':'music');
 const link=event.target.closest('.i-contents a');if(link){event.preventDefault();const section=document.querySelector(link.getAttribute('href'));section?.scrollIntoView({behavior:motion&&!matchMedia('(prefers-reduced-motion: reduce)').matches?'smooth':'instant',block:'start'});section?.querySelector('h2')?.focus({preventScroll:true})}
 const panel=document.querySelector('.i-audio[open]');if(panel&&!panel.contains(event.target))panel.open=false;
});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){const panel=document.querySelector('.i-audio[open]');if(panel){event.preventDefault();event.stopImmediatePropagation();panel.open=false;panel.querySelector('summary').focus()}}},true);

