// Standalone prototype state. +20 once per correct question, matching Espada rewards.ts.
const clarityEarned=new Set();
const clarityTopicStates={};
function clarityTopicProgress(i){return i===topicIndex?{read:[...readParts],attempts}:clarityTopicStates[i]||{read:[],attempts:[]}}
function clarityCompletedTopics(){return [0,1,2].filter(i=>clarityTopicProgress(i).attempts.length===3).length}
function clarityChooseTopic(i){
 if(i!==topicIndex){clarityTopicStates[topicIndex]={read:[...readParts],attempts:attempts.map(a=>({...a})),part,question,choice,checked,hinted};
  topicIndex=i;const saved=clarityTopicStates[i];readParts=new Set(saved?.read||[]);attempts=(saved?.attempts||[]).map(a=>({...a}));part=saved?.part||0;question=saved?.question||0;choice=saved?.choice??null;checked=saved?.checked||false;hinted=saved?.hinted||false;
 }
 go('lesson');
}
function clarityResetProgress(){clarityEarned.clear();for(const key of Object.keys(clarityTopicStates))delete clarityTopicStates[key]}
function clarityThemeButton(){return `<button class="i-theme-toggle" data-action="clarity-theme" aria-label="${dark?'Включить светлую тему':'Включить тёмную тему'}" title="${dark?'Светлая тема':'Тёмная тема'}"><svg class="i-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true">${dark?'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2"/>':'<path d="M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z"/>'}</svg></button>`}
function clarityPointsCard(){const points=clarityEarned.size*20,level=points>=300?2:points>=100?1:0,base=[0,100,300][level],next=[100,300,null][level],percent=next?Math.min(100,(points-base)/(next-base)*100):100;return `<section class="i-points-card" aria-label="Очки прогресса"><div class="i-points-top"><span class="i-level-badge" aria-hidden="true">${clarityIcon(level?'chart':'book')}</span><div><span class="i-eyebrow">УРОВЕНЬ ${level+1}</span><h2>${['Новичок','Исследователь','Знаток'][level]}</h2></div><strong class="i-points-number">${points}<span>очков</span></strong></div><div class="i-points-track" role="progressbar" aria-label="До следующего уровня" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.round(percent)}"><span style="width:${percent}%"></span></div><p>${next?`Ещё <strong>${next-points} очков</strong> до уровня «${['Исследователь','Знаток'][level]}»`:'Все уровни открыты!'}</p><span class="i-points-rule">+20 за верное задание · за каждое один раз</span></section>`}
function clarityMiniRadar(){const point=(i,value)=>{const a=i*Math.PI/3-Math.PI/2;return `${75+Math.cos(a)*52*value},${75+Math.sin(a)*52*value}`};return `<svg viewBox="0 0 150 150" class="i-mini-radar" aria-hidden="true">${[.33,.66,1].map(v=>`<polygon points="${radarAreas.map((_,i)=>point(i,v)).join(' ')}" fill="none" stroke="var(--line)" stroke-width="1.5"/>`).join('')}<polygon points="${radarAreas.map((a,i)=>point(i,a.current/a.total)).join(' ')}" fill="var(--radar-fill)" stroke="var(--primary)" stroke-width="3"/>${radarAreas.map((a,i)=>{const [x,y]=point(i,a.current/a.total).split(',');return `<circle cx="${x}" cy="${y}" r="3" fill="var(--primary)"/>`}).join('')}</svg>`}
