// Direction D: mathematical diagrams are interactive teaching material.
const discoveryFactors = {'1/2':2};
const discoveryTitles = ['Мир дробей','Чувство числа','Думай формами'];
function discDiagram(n,d,compact=false){
  const point=a=>[100+76*Math.cos(a),100+76*Math.sin(a)].map(v=>v.toFixed(3));
  const sectors=Array.from({length:d},(_,i)=>{const a=-Math.PI/2+i*2*Math.PI/d,b=a+2*Math.PI/d;return `<path class="d-sector ${i<n?'filled':''}" style="--sector:${i}" d="M100 100 L${point(a).join(' ')} A76 76 0 ${d===1?1:0} 1 ${point(b).join(' ')} Z"/>`}).join('');
  return `<svg class="d-disc ${compact?'compact':''}" viewBox="0 0 200 200" role="img" aria-label="${n} из ${d} равных частей закрашено"><circle class="d-disc-shadow" cx="104" cy="108" r="77"/>${sectors}<circle class="d-disc-edge" cx="100" cy="100" r="76"/></svg>`;
}
function discoveryExplorer(a=1,b=2){const key=`${a}/${b}`,factor=discoveryFactors[key]||2;return `<section class="d-explorer" data-base="${key}" aria-label="Исследователь равных дробей"><div class="d-explorer-top"><span class="d-mini-label">ПОПРОБУЙ САМ</span><span class="d-live-tag">Интерактив</span></div><div class="d-disc-wrap">${discDiagram(a*factor,b*factor)}<span class="d-fraction-stamp" aria-hidden="true">${a}/${b}</span></div><div class="d-equation" aria-live="polite">${frac([a,b])}<span>=</span><span class="d-equal-value">${frac([a*factor,b*factor])}</span></div><div class="d-slice-label"><span>Раздели каждую часть</span><output class="d-factor-label">на ${factor}</output></div><input class="d-slice-range" type="range" min="1" max="4" step="1" value="${factor}" aria-label="Во сколько раз разделить части" aria-valuetext="${factor} — получаем ${a*factor}/${b*factor}"><div class="d-range-ticks"><span>×1</span><span>×2</span><span>×3</span><span>×4</span></div><p class="d-explorer-caption">${factor===1?'Исходная дробь. Начни эксперимент.':'Частей больше. Величина та же.'}</p></section>`}
function discoveryArt(i){
  if(i===0)return `<div class="d-card-art d-art-fractions">${discDiagram(3,8,true)}<span class="d-art-equation">⅜</span></div>`;
  if(i===1)return `<div class="d-card-art d-art-numbers"><svg viewBox="0 0 300 160" role="img" aria-label="Разряды числа: сотни, десятки, единицы"><g class="d-number-block"><rect x="48" y="55" width="60" height="60" rx="9"/><text x="78" y="96" text-anchor="middle">4</text></g><g class="d-number-block"><rect x="120" y="32" width="60" height="60" rx="9"/><text x="150" y="73" text-anchor="middle">7</text></g><g class="d-number-block"><rect x="192" y="55" width="60" height="60" rx="9"/><text x="222" y="96" text-anchor="middle">0</text></g><path class="d-art-line" d="M38 131 H262"/></svg></div>`;
  return `<div class="d-card-art d-art-geometry"><svg viewBox="0 0 300 160" role="img" aria-label="Прямоугольный треугольник на координатной сетке"><path class="d-geo-grid" d="M70 15V145 M110 15V145 M150 15V145 M190 15V145 M230 15V145 M50 35H250 M50 75H250 M50 115H250"/><path class="d-triangle" d="M90 125 L90 35 L220 125 Z"/><path class="d-art-line" d="M90 108 H107 V125"/><circle cx="90" cy="35" r="4"/><circle cx="220" cy="125" r="4"/><circle cx="90" cy="125" r="4"/></svg></div>`;
}
function discoveryCards(items=topics.map((t,i)=>({...t,i}))){return items.map(t=>`<button class="d-course-card" data-topic="${t.i}">${discoveryArt(t.i)}<div class="d-course-copy"><span class="d-mini-label">${t.grade} КЛАСС <span>· 03 ШАГА</span></span><h3>${discoveryTitles[t.i]}</h3><p>${t.subtitle}</p><div class="d-course-bottom"><span>${t.i===topicIndex&&readParts.size?'Продолжить':'Исследовать'}</span><span class="d-circle-plus" aria-hidden="true">+</span></div></div></button>`).join('')}
function discoveryToday(){return `<div class="d-welcome"><div><span class="d-mini-label">МАЛЕНЬКИЙ ШАГ. БОЛЬШОЕ ОТКРЫТИЕ.</span><h1>Поймай <span class="d-highlight">идею.</span></h1><p>Привет, Алексей. Сегодня сложное станет понятным.</p></div><span class="d-day">05<span>ОКТЯБРЯ</span></span></div><section class="d-feature"><div class="d-feature-copy"><div class="d-chapter"><span class="d-chapter-number">01</span><span>ОТ УЧИТЕЛЯ<br><strong>Мир дробей</strong></span></div><h2>Одна половина.<br>Много способов.</h2><p>Почему ½ и ²⁄₄ — одно и то же?<br>Увидишь. Попробуешь. Поймёшь.</p><div class="d-feature-action">${btn(readParts.size&&topicIndex===0?'Продолжить открытие':'Начать открытие','assigned')}<span>3 части · 3 задания</span></div><div class="d-lesson-trail"><span class="current">Понять</span><i></i><span>Попробовать</span><i></i><span>Закрепить</span></div></div>${discoveryExplorer()}</section><div class="section-heading d-section-heading"><h2>Куда ведёт любопытство</h2><button class="text-link" data-go="learn">Все темы <span aria-hidden="true">↗</span></button></div><div class="d-course-grid">${discoveryCards()}</div><div class="d-teacher-note"><span class="d-note-symbol" aria-hidden="true">✎</span><div><strong>Обратная связь — тоже часть пути</strong><p>Есть оценка за работу по дробям. Посмотрим, что получилось?</p></div><button data-go="progress" class="text-link">Открыть результат</button></div>`}
function discoveryLearn(){return `<div class="d-welcome"><div><span class="d-mini-label">ТВОЯ КОЛЛЕКЦИЯ ОТКРЫТИЙ</span><h1>А что, <span class="d-highlight">если?</span></h1><p>Хорошие вопросы — начало больших идей.</p></div><span class="d-catalog-symbol" aria-hidden="true">?</span></div><div class="filters"><label class="search"><span class="sr-only">Найти тему</span><input id="search" type="search" placeholder="Какую идею исследуем?" autocomplete="off"></label><label><span class="sr-only">Класс</span><select id="grade"><option value="all">Все классы</option><option value="5">5 класс</option><option value="6">6 класс</option></select></label></div><div class="d-catalog-intro"><h2>Математика через открытия</h2><span class="d-mini-label">03 ДЕМО-ТЕМЫ</span></div><div id="topics" class="d-course-grid">${topicCards()}</div><div class="d-learning-promise"><span aria-hidden="true">↳</span><p><strong>Сначала «ага!», потом правило.</strong><br>Внутри каждой темы: понятная идея, пример и самостоятельная практика.</p></div>`}
function discoveryLesson(){const c=chapters[topicIndex][part];return `<div class="d-reading-steps" aria-label="Части урока">${chapters[topicIndex].map((_,i)=>`<button data-part="${i}" class="${i===part?'active':''}" aria-label="Часть ${i+1}: ${['Понимание','Правило','Пример'][i]}" ${i===part?'aria-current="step"':''}><i></i><span>0${i+1} ${['Понимание','Правило','Пример'][i]}</span></button>`).join('')}</div><div class="d-lesson-intro"><span class="d-mini-label">${topics[topicIndex].grade} КЛАСС / ${['ПОЧУВСТВУЙ ИДЕЮ','НАЙДИ ЗАКОНОМЕРНОСТЬ','ПРОВЕРЬ ДОГАДКУ'][part]}</span><h1>${c.title}</h1><p>${c.lead}</p></div><div class="d-lesson-grid"><article class="d-lesson-text"><h2>${c.heading}</h2><p>${c.text}</p><div class="d-aha"><span class="d-aha-symbol">!</span><div><strong>Вот в чём идея</strong><p>${c.rule}</p></div></div><div class="reader-controls">${part?btn('Назад','part-back','quiet'):'<span class="mini">Исследуй в своём темпе</span>'}${btn(part===2?'Теперь моя очередь':'Идея понятна','part-next')}</div></article>${topicIndex===0?discoveryExplorer(...[[1,2],[2,3],[3,5]][part]):`<aside class="d-concept-board">${discoveryArt(topicIndex)}<div class="d-concept-equation">${c.plain}</div><p>Сначала представь. Затем посчитай.</p></aside>`}</div>`}
function discoveryPractice(){return `<div class="d-practice-kicker"><span class="d-mini-label">ТВОЯ ОЧЕРЕДЬ</span><span class="d-spark" aria-hidden="true">✳</span></div>${practice()}<div class="d-practice-bottom"><span>Думать важнее, чем торопиться.</span><span>ESPADA / OPEN YOUR MIND</span></div>`}
function discoveryResult(){return `<div class="d-result-kicker"><span class="d-mini-label">МАЛЕНЬКИЕ ПОБЕДЫ СКЛАДЫВАЮТСЯ</span><span aria-hidden="true">✳</span></div>${result()} `}
function discoveryPage(){return ({today:discoveryToday,learn:discoveryLearn,lesson:discoveryLesson,practice:discoveryPractice,progress:discoveryResult,profile})[screen]()}
document.addEventListener('input',event=>{if(!event.target.matches('.d-slice-range'))return;const field=event.target,explorer=field.closest('.d-explorer'),[a,b]=explorer.dataset.base.split('/').map(Number),factor=Number(field.value);discoveryFactors[explorer.dataset.base]=factor;explorer.querySelector('.d-disc-wrap .d-disc').outerHTML=discDiagram(a*factor,b*factor);explorer.querySelector('.d-equal-value').innerHTML=frac([a*factor,b*factor]);explorer.querySelector('.d-factor-label').textContent=`на ${factor}`;explorer.querySelector('.d-explorer-caption').textContent=factor===1?'Исходная дробь. Начни эксперимент.':'Частей больше. Величина та же.';field.setAttribute('aria-valuetext',`${factor} — получаем ${a*factor}/${b*factor}`)});
