/* J — Duolingo study. Espada identity and lesson content, standalone demo. */
function duoIcon(name){const paths={
star:'<path d="m24 4 6 12 14 2-10 10 2 15-12-7-12 7 2-15L4 18l14-2Z" fill="#ffc800"/><path d="m24 10 4 9 10 1-8 7" fill="none" stroke="#ffdf65" stroke-width="3"/>',
fire:'<path d="M27 3c4 11-3 12 3 18 2-3 3-5 3-8 14 14 10 31-9 31S3 24 15 13c-1 7 2 8 3 8 5-5 1-11 9-18Z" fill="#ff9600"/><path d="M24 24c8 8 10 14 0 17-9-2-8-9 0-17Z" fill="#ffc800"/>',
gem:'<path d="m14 5 20 0 11 15-21 25L3 20Z" fill="#1cb0f6"/><path d="m14 5 10 15 10-15M3 20h42M24 20v25" fill="none" stroke="#80d8ff" stroke-width="3"/>',
heart:'<path d="M24 43 6 26C-6 12 10-2 24 10 38-2 54 12 42 26Z" fill="#ff4b4b"/><path d="M10 17q0-5 6-5" fill="none" stroke="#ffaaaa" stroke-width="4" stroke-linecap="round"/>',
book:'<path d="M6 8h30a5 5 0 0 1 5 5v28H12a6 6 0 0 1-6-6Z" fill="#1cb0f6"/><path d="M12 9v26h28M20 17h13M20 24h9" stroke="#9fe1ff" stroke-width="3" fill="none"/><path d="M12 36h29v6H12a3 3 0 0 1 0-6" fill="#e7f8ff"/>',
chest:'<path d="M6 23h36v17a4 4 0 0 1-4 4H10a4 4 0 0 1-4-4Z" fill="#e99300"/><path d="M6 23V14a8 8 0 0 1 8-8h20a8 8 0 0 1 8 8v9Z" fill="#ffc800"/><path d="M13 7v36m22-36v36" stroke="#ffdf63" stroke-width="5"/><path d="M4 23h40" stroke="#b56b00" stroke-width="4"/><rect x="18" y="20" width="12" height="12" rx="3" fill="#ffeaa0"/><path d="M24 24v4" stroke="#b56b00" stroke-width="3"/>',
trophy:'<path d="M14 5h20v14c0 8-5 12-10 12s-10-4-10-12Z" fill="#ffc800"/><path d="M14 9H6v7q0 9 11 9m17-16h8v7q0 9-11 9" stroke="#ffb000" stroke-width="5" fill="none"/><path d="M24 29v9m-9 4h18" stroke="#e7a300" stroke-width="7" stroke-linecap="round"/>',
check:'<path d="m10 24 10 10 19-22" fill="none" stroke="currentColor" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>',
flag:'<path d="M10 44V5" stroke="#9aa7ac" stroke-width="5" stroke-linecap="round"/><path d="M13 6h27l-5 10 5 10H13Z" fill="#ce82ff"/>',
map:'<path d="m4 12 13-7 14 7 13-7v31l-13 7-14-7-13 7Z" fill="#58cc02"/><path d="M17 6v29m14-22v29" stroke="#a5ed6e" stroke-width="3"/><circle cx="27" cy="22" r="8" fill="#ffcf47"/><path d="m24 21 3 4 5-8" stroke="#b58100" stroke-width="2.5" fill="none"/>',
};return `<svg class="j-icon" viewBox="0 0 48 48" aria-hidden="true">${paths[name]||paths.star}</svg>`}
function duoXP(){return clarityEarned.size*20}
function duoTotal(){return [0,1,2].reduce((sum,i)=>sum+clarityTopicProgress(i).attempts.length,0)}
function duoNav(){return `<nav class="j-nav" aria-label="Главное меню">${[['today','Учиться','map'],['learn','Темы','book'],['practice','Тренировка','star'],['progress','Мои успехи','trophy']].map(([id,label,icon])=>`<button data-go="${id}" ${screen===id?'aria-current="page"':''}>${duoIcon(icon)}<span>${label}</span></button>`).join('')}</nav>`}
function duoStats(){return `<div class="j-stats"><span title="Математика">${duoIcon('book')}<b>Математика</b></span><span title="Дней в этой демонстрации">${duoIcon('fire')}<b>${clarityCompletedTopics()?1:0}</b></span><button data-go="progress" aria-label="${duoXP()} очков опыта">${duoIcon('gem')}<b>${duoXP()}</b></button><span title="Неограниченные попытки">${duoIcon('heart')}<b>∞</b></span></div>`}
function duoRail(){return `<aside class="j-rail">${duoStats()}<section class="j-card j-daily"><div class="j-card-title"><h2>Цели на сегодня</h2>${duoIcon('chest')}</div>${duoQuest('Набери 60 очков',duoXP(),60,'star')}${duoQuest('Реши 3 задания',duoTotal(),3,'book')}<button class="j-text-link" data-go="progress">ПОСМОТРЕТЬ ПРОГРЕСС</button></section><section class="j-card j-streak">${duoIcon('fire')}<h2>${clarityCompletedTopics()?'Начало положено!':'Зажги свою серию'}</h2><p>${clarityCompletedTopics()?'Первое занятие готово. Так держать!':'Пройди одно занятие сегодня. Большие победы начинаются с малого.'}</p><div class="j-week" aria-label="Дни демонстрационной серии">${['П','В','С','Ч','П','С','В'].map((d,i)=>`<span class="${i===2&&clarityCompletedTopics()?'lit':''}">${d}<i>${i===2&&clarityCompletedTopics()?'✓':'·'}</i></span>`).join('')}</div></section><p class="j-demo-note">Дизайн-эксперимент · Espada<br>Очки и серия — в рамках этой демонстрации.</p></aside>`}
function duoQuest(label,value,total,icon){return `<div class="j-quest">${duoIcon(icon)}<div><strong>${label}</strong><div class="j-track" role="progressbar" aria-label="${label}" aria-valuemin="0" aria-valuemax="${total}" aria-valuenow="${Math.min(value,total)}"><i style="width:${Math.min(value/total,1)*100}%"></i><span>${Math.min(value,total)} / ${total}</span></div></div></div>`}
function duoShell(content,animate){if(isLessonScreen(screen))return `<div class="j-focus"><header class="j-focus-head"><button class="j-close" data-action="exit-lesson" aria-label="Выйти из урока">×</button><img src="assets/knight-${dark?'dark':'light'}.jpg" alt="Espada"><div class="j-track j-lesson-track" role="progressbar" aria-label="Завершено заданий" aria-valuemin="0" aria-valuemax="3" aria-valuenow="${attempts.length}"><i style="width:${attempts.length/3*100}%"></i></div><span class="j-lives">${duoIcon('heart')}∞</span>${clarityThemeButton()}${clarityTools()}</header><main class="j-focus-main ${animate?'scene':''}">${content}</main></div>`;
return `<div class="j-shell"><aside class="j-sidebar"><button class="j-brand" data-go="today" aria-label="Espada — главная"><img src="assets/knight-${dark?'dark':'light'}.jpg" alt="">espada<span>.</span></button>${duoNav()}<div class="j-sidebar-bottom"><div class="j-subject">${duoIcon('book')}<span>МАТЕМАТИКА<br><strong>Шаг за шагом</strong></span></div><div class="j-tools">${clarityThemeButton()}${clarityTools()}</div></div></aside><div class="j-mobile-head"><img src="assets/knight-${dark?'dark':'light'}.jpg" alt="Espada">${duoStats()}</div><div class="j-workspace"><main class="j-main ${animate?'scene':''}">${content}</main>${duoRail()}</div></div>`}
function duoMap(){return `<h1 class="sr-only">Твой путь в математике</h1>${[0,1,2].map(i=>duoUnit(i)).join('')}<div class="j-path-end">${duoIcon('flag')}<h2>Это только начало!</h2><p>Три темы. Девять маленьких побед.</p></div>`}
function duoUnit(i){const state=clarityTopicProgress(i),done=state.attempts.length===3,reading=state.read.length===3;return `<section class="j-unit j-unit-${i}" aria-label="${clarityTitles[i]}"><header class="j-unit-head"><div><span>РАЗДЕЛ ${i+1} · МАТЕМАТИКА</span><h2>${['Разберёмся с дробями','Подружимся с числами','Откроем мир фигур'][i]}</h2></div><button data-topic="${i}" aria-label="Открыть справочник: ${clarityTitles[i]}">${duoIcon('book')}<span>СПРАВОЧНИК</span></button></header><div class="j-path"><div class="j-path-line" aria-hidden="true"></div><div class="j-stop j-stop-0"><span class="j-start-label">${done?'ЕЩЁ РАЗ':i===topicIndex?'НАЧАТЬ':'ПОПРОБУЙ'}</span><button class="j-node ${reading?'is-done':'is-current'}" data-topic="${i}" aria-label="${clarityTitles[i]}: ${reading?'повторить':'открыть'} урок">${duoIcon(reading?'check':'star')}</button><span class="j-node-caption">${['Делим поровну','Числа и разряды','Стороны и углы'][i]}</span></div><div class="j-stop j-stop-1"><button class="j-node ${state.attempts.length?'is-done':'is-future'}" data-duo-practice="${i}" aria-label="${clarityTitles[i]}: практика">${duoIcon('book')}</button><span class="j-node-caption">Пробуем сами</span></div><div class="j-path-friend" aria-hidden="true"><div class="j-speech">${['У тебя получится!','Каждый шаг важен!','Ты растёшь!'][i]}</div><div class="j-number-friend"><span>${['½','7','△'][i]}</span><i></i><b></b></div><div class="j-friend-shadow"></div></div><div class="j-stop j-stop-2"><button class="j-node j-treasure ${done?'is-done':''}" data-go="progress" aria-label="Посмотреть награды">${duoIcon('chest')}</button><span class="j-node-caption">${[...clarityEarned].filter(k=>k.startsWith(i+':')).length*20} / 60 очков</span></div><div class="j-stop j-stop-3"><button class="j-node ${done?'is-done':'is-future'}" data-duo-practice="${i}" aria-label="${clarityTitles[i]}: ${done?'повторить задания':'завершить тему'}">${duoIcon(done?'check':'trophy')}</button><span class="j-node-caption">${done?'Тема пройдена!':'Закрепляем'}</span></div></div></section>`}
function duoTopicCards(){const found=topics.map((t,i)=>({...t,i})).filter(t=>(t.title+' '+t.subtitle).toLowerCase().includes(query.toLowerCase()));return found.length?found.map(t=>`<button class="j-topic-card j-unit-${t.i}" data-topic="${t.i}"><span class="j-topic-symbol">${['½','123','△'][t.i]}</span><span><small>РАЗДЕЛ ${t.i+1}</small><strong>${clarityTitles[t.i]}</strong><em>${t.subtitle}</em><span>${clarityTopicProgress(t.i).attempts.length} из 3 заданий · ${[...clarityEarned].filter(k=>k.startsWith(t.i+':')).length*20} очков</span></span><b>›</b></button>`).join(''):`<div class="j-card"><h2>Такой темы пока нет</h2><button class="j-button" data-action="clear-search">Показать все темы</button></div>`}
function duoLearn(){return `<div class="j-page-heading"><span>ТВОЯ БИБЛИОТЕКА</span><h1>Выбирай, что интересно</h1><p>Можно идти по пути, а можно начать с любимой темы.</p></div><label class="j-search" for="search">Найти тему<input id="search" type="search" placeholder="Дроби, числа, фигуры…"></label><select id="grade" hidden aria-label="Класс"><option value="all">Все классы</option></select><div id="topics">${duoTopicCards()}</div><button class="j-button j-outline" data-go="today">Вернуться на путь</button>`}
function duoPractice(){const q=activeQuestion(),correct=choice===q.correct;return `<section class="j-practice"><div class="j-exercise-kicker">${duoIcon('star')} ТРЕНИРУЕМСЯ · ${question+1} ИЗ 3</div><h1>${q.title}</h1><div class="j-question"><div class="j-small-friend" aria-hidden="true">${['½','7','△'][topicIndex]}</div><div class="j-question-bubble">${q.formula?frac(q.formula)+(q.equation?' = '+frac(q.equation):' = ?'):'Выбери верный ответ'}</div></div><div class="j-answer-list" role="group" aria-label="Варианты ответа">${q.answers.map((a,i)=>`<button class="j-answer i-answer ${choice===i?'selected':''} ${checked&&i===q.correct?'correct':''} ${checked&&choice===i&&!correct?'wrong':''}" data-choice="${i}" aria-label="${Array.isArray(a)?a.join('/'):a}${checked&&i===q.correct?', правильный ответ':checked&&choice===i?', твой ответ':''}" aria-pressed="${choice===i}" ${checked?'disabled':''}><small>${i+1}</small><span>${frac(a)}</span>${checked&&i===q.correct?duoIcon('check'):''}</button>`).join('')}</div>${hinted&&!checked?`<aside class="j-hint" role="status">${q.hint}</aside>`:''}<div class="j-answer-footer ${checked?correct?'good':'bad':''}"><div class="j-footer-inner">${checked?`<div class="j-feedback" role="status"><span class="j-feedback-symbol">${correct?'✓':'!'}</span><div><h2>${correct?'Отлично!':'Учимся на ошибках'}</h2><p>${q.explanation}</p></div></div><button class="j-button" data-action="question-next">${question===2?'Завершить':'Продолжить'}</button>`:`<button class="j-button j-outline" data-action="hint" ${hinted?'disabled':''}>Подсказка</button><button class="j-button" data-action="check" ${choice===null?'disabled':''}>Проверить</button>`}</div></div></section>`}
function duoProgress(){return `<div class="j-page-heading j-celebration">${duoIcon('trophy')}<span>КАЖДЫЙ ШАГ СЧИТАЕТСЯ</span><h1>${attempts.length===3?'Отличная работа!':'Твои успехи'}</h1><p>${attempts.length===3?'Ещё одна маленькая победа в твоей копилке.':'Смотри, как растёт твоя уверенность.'}</p></div><div class="j-result-stats"><div>${duoIcon('gem')}<strong>${duoXP()}</strong><span>ОЧКОВ ОПЫТА</span></div><div>${duoIcon('check')}<strong>${duoTotal()}</strong><span>ЗАДАНИЙ</span></div><div>${duoIcon('trophy')}<strong>${clarityCompletedTopics()}</strong><span>ТЕМ ПРОЙДЕНО</span></div></div>${clarityPointsCard()}<button class="j-button j-return" data-go="today">Продолжить путь</button>${clarityRadar()}<p class="j-demo-note">+20 очков за каждый верный ответ один раз. Прогресс хранится до перезагрузки.</p>`}
function duoPage(){return ({today:duoMap,learn:duoLearn,lesson:clarityLesson,practice:duoPractice,progress:duoProgress,profile:duoMap})[screen]()}
document.addEventListener('click',event=>{if(variant!=='j')return;const b=event.target.closest('[data-duo-practice]');if(b){clarityChooseTopic(Number(b.dataset.duoPractice));if(attempts.length===3)resetPractice();go('practice')}});
