/* Elements adapted from Espada: Theme, LearningArt, LevelCard, Home and LatestReport.
   Report/assignment examples are synthetic; practice data is this preview session only. */
function espadaNativeArt(kind){return flatArt(kind==='compass'?'progress':kind,'m-native-art m-flat-art')}
function espadaNativeLevel(){const points=duoXP(),levels=[{name:'Новичок',points:0},{name:'Исследователь',points:100},{name:'Знаток',points:300}],index=points>=300?2:points>=100?1:0,next=levels[index+1],percent=next?(points-levels[index].points)/(next.points-levels[index].points)*100:100;return `<section class="m-native-card m-native-level" aria-label="Уровень Espada"><div class="m-native-level-head"><span class="m-native-compass">${espadaNativeArt('league')}</span><div><span class="m-kicker">УРОВЕНЬ ${index+1} / 3</span><h2>${levels[index].name}</h2><strong>${points} очков</strong></div></div><div class="m-thin-track" role="progressbar" aria-label="${next?'До уровня '+next.name:'Все уровни открыты'}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.round(percent)}"><i style="width:${percent}%"></i></div><p>${next?`Ещё ${next.points-points} очков до уровня «${next.name}»`:'Все уровни открыты. Продолжай пополнять копилку!'}</p><details class="m-native-reveal"><summary>Как получить очки?</summary><p>+20 за верное задание, в том числе с подсказкой. За каждое — один раз.</p><ol>${levels.map(l=>`<li>${l.name} · от ${l.points}</li>`).join('')}</ol><small>В приложении также +10 за просмотр 80% видео. В этой площадке награда за видео ещё не подключена. Очки не меняют оценки учителя.</small></details></section>`}
function espadaReportInsights(){const measured=radarAreas.filter(a=>a.total>0),values=measured.map(a=>a.current/a.total),high=Math.max(...values),low=Math.min(...values);return {strong:measured.filter(a=>a.current/a.total===high),repeat:measured.filter(a=>a.current/a.total===low&&low<1),correct:measured.reduce((n,a)=>n+a.current,0),total:measured.reduce((n,a)=>n+a.total,0),improved:measured.filter(a=>a.current>a.previous).length,count:measured.length}}
function espadaReportTopic(area){return ({'Вычисления':1,'Дроби':0,'Геометрия':2})[area.label]}
function espadaNativeAssignment(){const done=clarityTopicProgress(0).attempts.length===3;return `<section class="m-native-card m-native-assignment"><div class="m-native-caption">${espadaIcon('book')}<span>От учителя</span><small>Пример</small></div><h2>Равные дроби</h2><p>Посмотри объяснение и реши три задания на сокращение дробей.</p><span class="m-native-status">${espadaIcon(done?'check':'training')}${done?'Практика завершена':clarityTopicProgress(0).attempts.length+' из 3 заданий решено'}</span><button class="m-text" data-m-native-topic="0" data-native-mode="lesson">${done?'Повторить урок':'Открыть задание'} ${espadaIcon('arrow')}</button></section>`}
function espadaNativeReportPreview(){const info=espadaReportInsights();return `<section class="m-native-card m-native-report-preview"><div class="m-native-caption"><span>Последний тест</span><small>Пример</small></div><div class="m-native-preview-chart">${clarityMiniRadar()}<div><strong>4<span> / 5</span></strong><small>Оценка учителя<br>2 октября</small></div></div><p>${info.correct} из ${info.total} верно · ${info.improved} разделов лучше</p><button class="m-text" data-go="progress">Карта результатов ${espadaIcon('arrow')}</button></section>`}
function espadaNativeReportSummary(){const info=espadaReportInsights();return `<section class="m-native-report-summary" aria-label="Результат офлайн-теста"><header><div><span class="m-kicker">ПОСЛЕДНИЙ ОФЛАЙН-ТЕСТ · УЧЕБНЫЙ ПРИМЕР</span><h2>Математика · 2 октября</h2><p>Работа учителя, отдельно от практики в приложении.</p></div><div class="m-native-grade" aria-label="Оценка 4 из 5"><strong>4</strong><span>из 5</span></div></header><div class="m-native-insights"><div><span class="m-native-insight-label">${espadaIcon('star')} Сильная сторона</span><h3>${info.strong.map(a=>a.label).join(' · ')}</h3><strong>${Math.round(info.strong[0].current/info.strong[0].total*100)}<span>% верно</span></strong></div><div><span class="m-native-insight-label">${espadaIcon('training')} Немного практики</span><h3>${info.repeat.map(a=>a.label).join(' · ')||'Все разделы освоены'}</h3>${info.repeat[0]?`<strong>${Math.round(info.repeat[0].current/info.repeat[0].total*100)}<span>% верно</span></strong><button class="m-text" ${espadaReportTopic(info.repeat[0])!==undefined?`data-m-native-topic="${espadaReportTopic(info.repeat[0])}" data-native-mode="practice"`:'data-go="learn"'}>Потренироваться ${espadaIcon('arrow')}</button>`:'<p>Можно выбрать новую тему.</p>'}</div></div><div class="m-native-report-totals"><span><strong>${info.correct} / ${info.total}</strong> ответов верно</span><span><strong>↑ ${info.improved} / ${info.count}</strong> разделов лучше</span></div></section>`}
function espadaNativeRecommendations(){const info=espadaReportInsights();return `<section class="m-native-recommendations"><div class="m-section-head"><h2>Что повторить</h2><span>По тесту · пример</span></div>${info.repeat.map(a=>`<div class="m-native-repeat"><span class="m-native-repeat-art">${espadaNativeArt(topicIllustration(a.label))}</span><div><h3>${a.label}</h3><p>${a.current} из ${a.total} верно. Этот раздел полезно закрепить.</p></div><button class="m-primary" ${espadaReportTopic(a)!==undefined?`data-m-native-topic="${espadaReportTopic(a)}" data-native-mode="practice"`:'data-go="learn"'}>Выбрать ${espadaIcon('arrow')}</button></div>`).join('')}</section>`}
function espadaNativeMistakes(){const mistakes=topics.flatMap((t,i)=>clarityTopicProgress(i).attempts.map((a,q)=>({...a,i,q}))).filter(a=>!a.correct);return `<section class="m-native-mistakes"><div class="m-section-head"><h2>Разобрать ошибки</h2><span>${mistakes.length?mistakes.length+' в этой сессии':'Пока пусто'}</span></div>${mistakes.length?mistakes.map(a=>{const q=a.i===0?clarityFractionQuestions[a.q]:banks[a.i][a.q];return `<details class="m-native-mistake"><summary><span>${topics[a.i].title}</span><strong>${q.title}</strong></summary><div><p>Твой ответ: <b>${frac(q.answers[a.choice])}</b></p><p>Правильный ответ: <b>${frac(q.answers[q.correct])}</b></p><p>${q.explanation}</p><button class="m-text" data-m-native-topic="${a.i}" data-native-mode="read">Вернуться к объяснению ${espadaIcon('arrow')}</button></div></details>`}).join(''):`<div class="m-native-empty">${espadaIcon('check')}<p>Здесь появятся задачи, в которых ты ошибся. К ним можно вернуться и разобраться.</p></div>`}</section>`}
document.addEventListener('click',e=>{if(variant!=='m')return;const b=e.target.closest('[data-m-native-topic]');if(!b)return;const i=Number(b.dataset.mNativeTopic),mode=b.dataset.nativeMode;referenceReady=false;referenceLessonMode=mode==='read'?'read':'overview';clarityChooseTopic(i);go(mode==='practice'?'practice':'lesson')});

// Adapted from the main app's VisualCard: illustration, title and corner arrow.
function espadaNativeShortcuts(){return `<nav class="m-native-shortcuts" aria-label="Быстрые переходы"><button class="m-native-shortcut" data-go="learn"><span class="m-native-shortcut-arrow">${espadaIcon('arrow')}</span><span class="m-native-shortcut-art">${espadaNativeArt('numbers')}</span><strong>Все темы</strong><span class="m-native-shortcut-caption">Выбери своё открытие</span></button><button class="m-native-shortcut" data-go="progress"><span class="m-native-shortcut-arrow">${espadaIcon('arrow')}</span><span class="m-native-shortcut-art">${espadaNativeArt('compass')}</span><strong>Мой прогресс</strong><span class="m-native-shortcut-caption">${duoXP()} очков · карта знаний</span></button></nav>`}
