const screens=['today','learn','lesson','practice','progress','profile'];
const names=['Сегодня','Каталог тем','Урок','Практика','Мой прогресс','Лига'];
const directions={m:['Espada · Линия','Родная Espada: дерево уроков, оливковая палитра, задания учителя, уровни и карта результатов.'],l:['Дуо · Референсы','По вашим скриншотам: тёмная палитра, округлый шрифт, каталог классов и тем, игровой путь, лига и новое оформление заданий.'],j:['Дуо','Эксперимент по мотивам Duolingo: путь с объёмными узлами, яркие цвета, игровые цели и отдельный экран задания.'],i:['Ясно','Зелёная Espada: родной знак, маршрут тем, очки и открытая карта знаний. Цельные уроки, музыка, светлая и тёмная версии.'],f:['Импульс','Вдохновение — Elevate. Короткие тренировки, контрастные блоки и заметный результат каждого занятия.'],g:['Тепло','Вдохновение — Headspace. Мягкие формы, тёплые иллюстрации и дружелюбное приглашение учиться.'],h:['Атлас','Вдохновение — Khan Academy. Карта курса, чёткая структура и прозрачный прогресс.'],e:['Тишина','Простота в пропорциях, воздухе и типографике. Один акцент, спокойные цвета и только нужные действия.'],d:['Эврика','Понимание через действие. Контрастная типографика, лаймовый акцент и живая математика. Референс — Brilliant.'],a:['Знакомая Espada','Сохраняем тёплый характер. Уменьшаем декор и раньше показываем полезное действие.'],b:['В фокусе','Одна заметная задача, спокойный каталог и больше места для чтения.'],c:['Мой маршрут','Видно, что уже сделано и какой шаг дальше. Игра помогает ориентироваться.']};
const $=s=>document.querySelector(s), frame=$('#preview');
let state={variant:'i',screen:'today',device:'desktop',dark:false,motion:true},notes={};
try{const saved=JSON.parse(localStorage.getItem('espada-lab-settings')||'null');if(saved&&directions[saved.variant]&&screens.includes(saved.screen))state={...state,...saved};const parsed=JSON.parse(localStorage.getItem('espada-lab-notes')||'{}');if(parsed&&typeof parsed==='object'&&!Array.isArray(parsed))notes=parsed;}catch{}
const launchParams=new URLSearchParams(location.search);if(directions[launchParams.get('v')])state.variant=launchParams.get('v');if(state.variant==='l')state.dark=true;if(state.variant==='m')state.dark=false;if(screens.includes(launchParams.get('screen')))state.screen=launchParams.get('screen');
function noteKey(){return `${state.variant}/${state.screen}`}
function send(){frame.contentWindow.postMessage({type:'espada-lab-config',...state},location.protocol==='file:'?'*':location.origin)}
function viewScreens(){return ['l','m'].includes(state.variant)?screens:screens.filter(s=>s!=='profile')}
function update(){if(!viewScreens().includes(state.screen))state.screen='today';$('#league-screen').hidden=!['l','m'].includes(state.variant);document.querySelectorAll('[data-variant]').forEach(b=>{const active=b.dataset.variant===state.variant;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active)});document.querySelectorAll('[data-screen]').forEach(b=>b.classList.toggle('active',b.dataset.screen===state.screen));document.querySelectorAll('[data-device]').forEach(b=>{const active=b.dataset.device===state.device;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active)});$('.stage').classList.toggle('mobile',state.device==='mobile');$('.stage').classList.toggle('narrow',state.device==='narrow');$('#standalone').href=`preview.html?v=${state.variant}&screen=${state.screen}&dark=${state.dark?1:0}&motion=${state.motion?1:0}`;$('#hypothesis').textContent=directions[state.variant][1];const references={l:['Ваши референсы · Duolingo','https://www.duolingo.com/'],j:['Duolingo','https://blog.duolingo.com/new-duolingo-home-screen-design/'],d:['Brilliant','https://brilliant.org/math/'],f:['Elevate','https://themindcompany.com/apps/elevate'],g:['Headspace','https://www.headspace.com/app'],h:['Khan Academy','https://support.khanacademy.org/hc/en-us/articles/115002552631-What-are-Course-and-Unit-Mastery']};const ref=references[state.variant];$('#direction-reference').hidden=!ref;if(ref){$('#direction-reference').textContent=`Референс: ${ref[0]} ↗`;$('#direction-reference').href=ref[1]}$('#preview-title').textContent=`${state.variant.toUpperCase()} / ${directions[state.variant][0]}`;$('#dimensions').textContent=state.device==='narrow'?'320 px · узкий экран':state.device==='mobile'?'390 px · мобильный сценарий':'Адаптивная ширина';$('#current-screen').textContent=names[screens.indexOf(state.screen)];$('#screen-count').textContent=`0${viewScreens().indexOf(state.screen)+1} / 0${viewScreens().length}`;$('#notes').value=notes[noteKey()]||'';$('#theme').setAttribute('aria-pressed',state.dark);$('#theme').textContent=state.dark?'Светлая тема':'Тёмная тема';$('#motion').checked=state.motion;document.body.classList.toggle('no-motion',!state.motion);try{localStorage.setItem('espada-lab-settings',JSON.stringify(state))}catch{}send()}
document.querySelectorAll('[data-variant]').forEach(b=>b.onclick=()=>{state.variant=b.dataset.variant;if(state.variant==='l')state.dark=true;if(state.variant==='m')state.dark=false;update()});document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>{state.screen=b.dataset.screen;update()});document.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>{state.device=b.dataset.device;update()});
$('#theme').onclick=()=>{state.dark=!state.dark;update()};$('#motion').onchange=e=>{state.motion=e.target.checked;update()};
function step(n){const visible=viewScreens();state.screen=visible[(visible.indexOf(state.screen)+n+visible.length)%visible.length];update()}
$('#prev').onclick=()=>step(-1);$('#next').onclick=()=>step(1);
$('#notes').oninput=e=>{notes[noteKey()]=e.target.value;try{localStorage.setItem('espada-lab-notes',JSON.stringify(notes));$('#save-status').textContent='Сохранено в этом браузере'}catch{$('#save-status').textContent='Используйте экспорт для сохранения'}};
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify({project:'Espada Design Lab',version:1,exportedAt:new Date().toISOString(),notes},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='espada-design-notes.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('#audit-open').onclick=()=>$('#audit').showModal();$('#audit-close').onclick=()=>$('#audit').close();$('#audit').onclick=e=>{if(e.target===$('#audit')&&e.clientX<$('#audit').getBoundingClientRect().left)$('#audit').close()};
$('#restart').onclick=()=>frame.contentWindow.postMessage({type:'espada-lab-reset'},location.protocol==='file:'?'*':location.origin);
window.addEventListener('message',e=>{if(e.source!==frame.contentWindow||(location.protocol!=='file:'&&e.origin!==location.origin))return;if(e.data?.type==='espada-lab-ready')send();if(e.data?.type==='espada-lab-theme'&&typeof e.data.dark==='boolean'){state.dark=e.data.dark;update()}if(e.data?.type==='espada-lab-screen'&&screens.includes(e.data.screen)){state.screen=e.data.screen;update()}});
window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||$('#audit').open)return;if(e.key==='ArrowRight'){e.preventDefault();step(1)}if(e.key==='ArrowLeft'){e.preventDefault();step(-1)}});frame.onload=send;update();
