const app=document.getElementById('app');
const screenNames={today:'Сегодня',learn:'Каталог тем',lesson:'Урок',practice:'Практика',progress:'Мой прогресс',profile:'Профиль'};
let variant='a',screen='today',dark=false,motion=true,part=0,question=0,choice=null,checked=false,hinted=false,query='',grade='all',topicIndex=0;
let attempts=[],readParts=new Set();
const topics=[{title:'Обыкновенные дроби',grade:5,image:'topic-fractions.jpg',subtitle:'Равные дроби и сокращение',parts:3},{title:'Натуральные числа',grade:5,image:'topic-numbers.jpg',subtitle:'Разряды и порядок действий',parts:3},{title:'Геометрические фигуры',grade:6,image:'topic-geometry.jpg',subtitle:'Периметр и площадь',parts:3}];
const banks=[[
{title:'Найди равную дробь',formula:['1','2'],answers:[['2','4'],['1','4'],['2','3']],correct:0,hint:'Умножь числитель и знаменатель на одно и то же число: на 2.',explanation:'1 × 2 = 2, а 2 × 2 = 4. Поэтому 1/2 = 2/4.'},
{title:'Сократи дробь',formula:['6','9'],answers:[['3','9'],['2','3'],['1','3']],correct:1,hint:'Числа 6 и 9 делятся на 3. Раздели на 3 и числитель, и знаменатель.',explanation:'6 ÷ 3 = 2, а 9 ÷ 3 = 3. Получаем 2/3.'},
{title:'Какое число пропущено?',formula:['3','5'],equation:['?','10'],answers:['3','6','8'],correct:1,hint:'Знаменатель увеличился в 2 раза. Во столько же раз увеличь числитель.',explanation:'5 × 2 = 10, поэтому 3 × 2 = 6. Равная дробь — 6/10.'}
],[
{title:'Сколько десятков в числе 470?',answers:['4','47','470'],correct:1,hint:'Раздели 470 на 10.',explanation:'В числе 470 содержится 47 десятков.'},
{title:'Вычисли: 6 + 3 × 4',answers:['36','18','24'],correct:1,hint:'Сначала выполни умножение.',explanation:'3 × 4 = 12, затем 6 + 12 = 18.'},
{title:'Вычисли: (6 + 3) × 4',answers:['18','24','36'],correct:2,hint:'Сначала выполни действие в скобках.',explanation:'6 + 3 = 9, затем 9 × 4 = 36.'}
],[
{title:'Найди периметр квадрата со стороной 4 см',answers:['8 см','16 см','12 см'],correct:1,hint:'У квадрата четыре равные стороны.',explanation:'4 + 4 + 4 + 4 = 16 см.'},
{title:'Найди площадь прямоугольника 3 × 5 см',answers:['15 см²','16 см²','8 см²'],correct:0,hint:'Умножь длину на ширину.',explanation:'3 × 5 = 15 см².'},
{title:'Найди площадь квадрата со стороной 6 см',answers:['24 см²','12 см²','36 см²'],correct:2,hint:'Площадь квадрата равна произведению двух его сторон.',explanation:'6 × 6 = 36 см².'}
]];
const chapters=[[
{title:'Одна величина — разные записи',lead:'Научимся узнавать равные дроби и объяснять, почему они равны.',heading:'Дробь меняется. Значение — нет.',text:'Половину можно записать как 1/2 или как 2/4. Мы разделили каждую из двух частей ещё пополам. Частей стало больше, но сама величина не изменилась.',math:[['1','2'],['2','4']],rule:'Если числитель и знаменатель умножить на одно и то же ненулевое число, получится равная дробь.'},
{title:'Сокращаем дробь',lead:'Обратное действие помогает сделать запись короче.',heading:'Раздели обе части на одно число',text:'Числитель и знаменатель дроби 6/9 делятся на 3. Делим оба числа на 3 и получаем более простую запись той же величины.',math:[['6','9'],['2','3']],rule:'Чтобы сократить дробь, раздели числитель и знаменатель на их общий делитель.'},
{title:'Проверяем на примере',lead:'Теперь попробуем применить правило самостоятельно.',heading:'Как из 3/5 получить десятые?',text:'Чтобы знаменатель 5 стал равен 10, его нужно умножить на 2. Значит, числитель 3 тоже умножаем на 2 и получаем 6.',math:[['3','5'],['6','10']],rule:'Всегда выполняй одинаковое действие с числителем и знаменателем. Теперь переходи к трём коротким заданиям.'}
],[
{title:'Числа и разряды',lead:'Посмотрим, как место цифры меняет её значение.',heading:'У каждого разряда своё место',text:'В числе 470 цифра 4 обозначает четыре сотни, а цифра 7 — семь десятков. Четыре сотни — это 40 десятков. Всего получаем 47 десятков.',plain:'470 = 400 + 70',rule:'Чтобы узнать число полных десятков, раздели число на 10 и возьми целую часть.'},
{title:'Порядок действий',lead:'Порядок важен даже в коротком выражении.',heading:'Умножение выполняют первым',text:'В выражении 6 + 3 × 4 сначала вычислим 3 × 4. Получится 12. После этого прибавим 6.',plain:'6 + 3 × 4 = 18',rule:'Если скобок нет, сначала выполняют умножение и деление, затем сложение и вычитание.'},
{title:'Скобки меняют порядок',lead:'Сначала посчитаем то, что внутри скобок.',heading:'Начни со скобок',text:'В выражении (6 + 3) × 4 сначала складываем 6 и 3. Затем умножаем полученные 9 на 4.',plain:'(6 + 3) × 4 = 36',rule:'Сначала действия в скобках, затем умножение и деление, после — сложение и вычитание.'}
],[
{title:'Периметр',lead:'Считаем длину всей границы фигуры.',heading:'Сложи длины всех сторон',text:'У квадрата четыре одинаковые стороны. Если сторона равна 4 см, периметр равен 4 + 4 + 4 + 4 = 16 см.',plain:'P = 4 × 4 = 16 см',rule:'Периметр — сумма длин всех сторон. Его измеряют в единицах длины.'},
{title:'Площадь прямоугольника',lead:'Считаем, сколько места занимает фигура.',heading:'Умножь длину на ширину',text:'Прямоугольник со сторонами 3 см и 5 см можно заполнить пятнадцатью квадратами 1 × 1 см.',plain:'S = 3 × 5 = 15 см²',rule:'Площадь прямоугольника равна произведению длины и ширины.'},
{title:'Площадь квадрата',lead:'У квадрата длина и ширина одинаковые.',heading:'Умножь сторону на саму себя',text:'Если сторона квадрата равна 6 см, его площадь равна 6 × 6 = 36 см².',plain:'S = 6 × 6 = 36 см²',rule:'Площадь измеряют в квадратных единицах. Не путай её с периметром.'}
]];
const frac=a=>Array.isArray(a)?`<span class="frac"><span>${a[0]}</span><span>${a[1]}</span></span>`:a;
const btn=(text,action,cls='')=>`<button class="button ${cls}" data-action="${action}">${text}</button>`;
function nav(cls){return `<nav class="${cls}" aria-label="Основная навигация">${[['today','Сегодня','⌂'],['learn','Учиться','▤'],['progress','Мой прогресс','▥']].map(([id,label,icon])=>`<button data-go="${id}" class="${screen===id||(['lesson','practice'].includes(screen)&&id==='learn')?'active':''}" ${screen===id?'aria-current="page"':''}>${cls==='bottom-nav'?`<span class="nav-icon" aria-hidden="true">${icon}</span>`:''}${label}</button>`).join('')}</nav>`}
function header(title,subtitle){return `<div class="greeting"><div><h1>${title}</h1><p>${subtitle}</p></div><span class="date">5 октября · понедельник</span></div>`}
function teacher(){return `<span class="eyebrow subtle">Последняя работа · демо</span><div class="grade">4 <span>/ 5</span></div><p>Обыкновенные дроби</p><p class="mini">Оценка учителя · 2 октября</p><button class="text-link" data-go="progress">Посмотреть результат</button>`}
function hero(){return `<div class="hero"><div class="hero-copy"><span class="eyebrow">Задание от Марии Соколовой</span><h2>Разберёмся<br>с дробями</h2><p>Основное свойство дроби · 5 класс</p>${variant==='b'?`<div class="focus-meta"><div>В теме<strong>3 короткие части</strong></div><div>После урока<strong>3 задания</strong></div></div>`:''}${btn(readParts.size?'Продолжить урок':'Начать задание','assigned')}</div><img src="assets/learning-hero.png" alt=""></div>`}
function rows(){return `<div class="task-list"><button class="task-row" data-topic="1"><span class="number">01</span><span><strong>Натуральные числа</strong><small>Повторить порядок действий</small></span><span class="row-end">Открыть</span></button><button class="task-row" data-topic="2"><span class="number">02</span><span><strong>Геометрические фигуры</strong><small>Для самостоятельного изучения</small></span><span class="row-end">Открыть</span></button></div>`}
function today(){let greeting=header('Привет, Алексей!','Небольшой шаг к большому пониманию.');if(variant==='b')return greeting+`<div class="focus-layout"><div>${hero()}<div class="focus-schedule"><div class="section-heading"><h2>После основного задания</h2><button class="text-link" data-go="learn">Все темы</button></div>${rows()}</div></div><aside class="focus-aside"><h3>Обратная связь учителя</h3>${teacher()}</aside></div>`;if(variant==='c')return greeting+`<div class="route-header"><span class="route-mark" aria-hidden="true">⅔</span><div><h2>Сегодня — дроби</h2><p>Один маршрут, три понятных шага</p></div><span class="pill">5 класс</span></div><div class="route-layout"><div class="route"><div class="route-step current"><span class="route-node">1</span><div class="route-card"><span class="eyebrow subtle">${readParts.size===3?'Прочитано':'Начнём с понимания'}</span><h3>Разобраться в правиле</h3><p>Основное свойство дроби · 3 части</p>${btn(readParts.size?'Продолжить урок':'Открыть урок','assigned')}</div></div><div class="route-step"><span class="route-node">2</span><div class="route-card"><span class="eyebrow subtle">Закрепим</span><h3>Попробовать самому</h3><p>Три задания. Подсказка всегда рядом.</p><button class="text-link" data-go="practice">Перейти к практике</button></div></div><div class="route-step"><span class="route-node">3</span><div class="route-card"><span class="eyebrow subtle">Подведём итог</span><h3>Понять свой результат</h3><p>Что получилось и что ещё повторить.</p><button class="text-link" data-go="progress">Мой прогресс</button></div></div></div><aside class="route-side"><img src="assets/learning-hero.png" alt=""><div class="panel">${teacher()}</div></aside></div>`;return greeting+hero()+`<div class="home-grid"><section class="panel"><h3>Ещё можно позаниматься</h3>${rows()}</section><section class="panel">${teacher()}</section></div><button class="text-link" data-go="learn" style="margin-top:15px">Посмотреть все темы</button>`}
function topicCards(){if(variant==='j')return duoTopicCards();const found=topics.map((t,i)=>({...t,i})).filter(t=>(variant==='i'||grade==='all'||String(t.grade)===grade)&&(t.title+' '+t.subtitle+(variant==='d'?' '+discoveryTitles[t.i]:'')).toLowerCase().includes(query.toLowerCase()));if(variant==='d'&&found.length)return discoveryCards(found);if(variant==='e'&&found.length)return simpleRows(found);if(isExperiment()&&found.length)return experimentCards(found);if(variant==='i')return found.length?clarityCards(found):`<div class="i-empty"><h2>Такой темы нет</h2><p>Попробуй другое слово.</p>${clarityButton('Показать все темы','clear-search',true,'book')}</div>`;return found.length?found.map(t=>`<button class="topic" data-topic="${t.i}"><img class="topic-img" src="assets/${t.image}" alt=""><div class="topic-body"><span class="eyebrow">${t.grade} класс · Математика</span><h3>${t.title}</h3><p>${t.parts} части · 3 задания</p><span class="topic-tag">${t.i===topicIndex&&readParts.size?'Продолжить':'Начать тему'}</span>${t.i===topicIndex&&readParts.size?`<div class="topic-progress" role="progressbar" aria-label="Прочитано частей" aria-valuenow="${readParts.size}" aria-valuemin="0" aria-valuemax="3"><i style="width:${readParts.size/3*100}%"></i></div>`:''}</div></button>`).join(''):`<div class="empty"><h3>Такой темы пока нет</h3><p>Попробуй другое название или выбери все классы.</p>${btn('Сбросить поиск','clear-search','secondary')}</div>`}
function learn(){return header('Чему научимся?','Выбери тему. Объяснение и задания уже внутри.')+`<div class="filters"><label class="search"><span class="sr-only">Найти тему</span><input id="search" type="search" placeholder="Найти тему…" autocomplete="off"></label><label><span class="sr-only">Класс</span><select id="grade"><option value="all">Все классы</option><option value="5">5 класс</option><option value="6">6 класс</option></select></label></div><div class="section-heading"><h2>${variant==='c'?'Выбери свой маршрут':'Темы для изучения'}</h2><span class="mini">Демо-каталог · 3 темы</span></div><div id="topics" class="topics ${variant==='b'?'list':variant==='c'?'route-topics':''}">${topicCards()}</div><p class="fineprint">В площадке показаны три темы для проверки навигации. Полный курс остаётся в основном приложении.</p>`}
function lesson(){let c=chapters[topicIndex][part];return `<div class="breadcrumb"><button data-go="learn">Все темы</button><span>/</span><span>${topics[topicIndex].title}</span></div><div class="lesson-layout"><aside class="lesson-outline" aria-label="Содержание урока"><span class="eyebrow subtle">В ЭТОЙ ТЕМЕ</span>${chapters[topicIndex].map((c,i)=>`<button data-part="${i}" class="${part===i?'active':''}" ${part===i?'aria-current="step"':''}>${readParts.has(i)?'✓':i+1} · ${['Понимание','Правило','Пример'][i]}</button>`).join('')}<button data-go="practice">4 · Практика</button></aside><article class="lesson-content"><span class="eyebrow subtle">${topics[topicIndex].grade} класс · часть ${part+1} из 3</span><h1>${c.title}</h1><p class="lead">${c.lead}</p><div class="reader"><h2>${c.heading}</h2><p>${c.text}</p><div class="math" aria-label="${c.math?c.math.map(a=>a.join('/')).join(' равно '):c.plain}">${c.math?c.math.map(frac).join('<span>=</span>'):c.plain}</div><div class="rule"><strong>Запомни</strong><br>${c.rule}</div></div><div class="reader-controls">${part>0?btn('Назад','part-back','quiet'):'<span class="subtle">В своём темпе</span>'}${btn(part===2?'К практике':'Понятно, дальше','part-next')}</div><p class="fineprint">Чтение и результаты заданий учитываются отдельно.</p></article></div>`}
function practice(){let q=banks[topicIndex][question];return `<div class="practice-header"><h1>Попробуй сам</h1><button class="text-link" data-go="lesson">Вернуться к правилу</button></div><section class="exercise"><div class="exercise-top"><span class="pill">Задание ${question+1} из 3</span><span class="subtle">${topics[topicIndex].title}</span></div><div class="practice-track" role="progressbar" aria-label="Выполнено заданий" aria-valuemin="0" aria-valuemax="3" aria-valuenow="${attempts.length}"><i style="width:${attempts.length/3*100}%"></i></div><h2 class="question-title">${q.title}</h2>${q.formula?`<div class="question-formula" aria-label="${q.formula.join('/')} ${q.equation?'равно '+q.equation.join('/'):''}">${frac(q.formula)}${q.equation?' = '+frac(q.equation):''}</div>`:''}<div class="answers" role="group" aria-label="Варианты ответа">${q.answers.map((a,i)=>`<button class="answer ${choice===i?'selected':''} ${checked&&i===q.correct?'correct':''} ${checked&&choice===i&&i!==q.correct?'wrong':''}" data-choice="${i}" aria-label="${Array.isArray(a)?a.join('/'):a}" aria-pressed="${choice===i}" ${checked?'disabled':''}>${frac(a)}</button>`).join('')}</div>${hinted?`<div class="hint"><strong>Подсказка</strong><br>${q.hint}</div>`:''}${checked?`<div class="feedback ${choice!==q.correct?'error':''}" role="status"><h3>${choice===q.correct?(hinted?'Верно, с подсказкой':'Всё верно!'):'Пока не получилось. Разберём вместе.'}</h3><p>${q.explanation}</p></div>`:''}<div class="exercise-actions">${checked?btn(question===2?'Посмотреть результат':'Следующее задание','question-next'): `<button class="button" data-action="check" ${choice===null?'disabled':''}>Проверить ответ</button><button class="button quiet" data-action="hint" ${hinted?'disabled':''}>${hinted?'Подсказка открыта':'Нужна подсказка'}</button>`}</div><p class="fineprint">${checked?'Ответ сохранён в этой демонстрации.':'Можно ошибаться. Подсказка поможет понять ход решения.'}</p></section>`}
function result(fromPractice=false){const independent=attempts.filter(a=>a.correct&&!a.hinted).length,assisted=attempts.filter(a=>a.correct&&a.hinted).length,wrong=attempts.filter(a=>!a.correct).length;return header(fromPractice?'Практика завершена':'Мой прогресс',attempts.length?'Смотрим на понимание, а не только на цифры.':'Каждое занятие добавляет немного уверенности.')+`${variant==='d'?discoveryRadar():''}<div class="result-layout"><section class="panel result-panel"><span class="eyebrow subtle">Практика · ${topics[topicIndex].title}</span><h2>${attempts.length===3?'Три шага позади':attempts.length?'Продолжим начатое?':'Начнём с первой практики'}</h2><p>${attempts.length?`Проверено ${attempts.length} из 3 заданий`:'Результат появится после проверки ответов.'}</p><div class="result-numbers"><div><strong>${independent}</strong><span>Самостоятельно</span></div><div><strong>${assisted}</strong><span>С подсказкой</span></div><div><strong>${wrong}</strong><span>Ошибок</span></div></div>${attempts.length?`<div class="result-strip" aria-label="${independent} самостоятельно, ${assisted} с подсказкой, ${wrong} ошибок">${attempts.map(a=>`<i class="${!a.correct?'missed':a.hinted?'assisted':''}"></i>`).join('')}</div><div class="result-details"><h3>Что дальше</h3><p>${wrong?'Вернись к правилу и разбери задания, в которых была ошибка.':assisted?'Попробуй ещё раз без подсказок, когда будешь готов.':'Хороший шаг. Попробуй применить правило в новой теме.'}</p></div>`:''}${attempts.length===3?btn('Разобрать правило','review','secondary'):btn(attempts.length?'Продолжить практику':'Попробовать практику','practice')}</section><section class="panel"><span class="eyebrow subtle">Оценка учителя · демо</span><div class="grade">4 <span>/ 5</span></div><h3>Обыкновенные дроби</h3><p>Мария Соколова · 2 октября</p><div class="stat-line"><span>Верно в работе</span><strong>8 из 10</strong></div><div class="stat-line"><span>Шкала оценки</span><strong>1–5</strong></div><p class="fineprint">Это отдельная оценка за работу. Практика в площадке её не меняет.</p></section></div><div class="next-topic"><div><h3>Изучение текущей темы</h3><p>Прочитано ${readParts.size} из 3 частей · чтение не означает освоение</p></div>${btn(readParts.size?'Продолжить чтение':'Открыть урок','review','secondary')}</div>${attempts.length===3?`<div style="margin-top:20px">${btn('Повторить практику','retry','quiet')} ${btn('Выбрать другую тему','learn','quiet')}</div>`:''}`}
function profile(){return `<section class="panel profile-card"><span class="eyebrow subtle">Демонстрационный профиль</span><h1>Алексей Морозов</h1><p>Ученик · 5 класс</p><p style="margin:18px 0">В этой площадке проверяем сценарий ученика. Настоящие учётные записи и данные не подключены.</p>${btn('Вернуться к занятиям','today')}</section>`}
function render(animate=true){const focus=document.activeElement;const focusKey=focus?.dataset?.choice!==undefined?['choice',focus.dataset.choice]:focus?.dataset?.action?['action',focus.dataset.action]:null;document.body.dataset.variant=variant;document.body.classList.toggle('dark',dark);document.body.classList.toggle('no-motion',!motion);const focused=['d','e','f','g','h','i','j','l','m'].includes(variant)&&isLessonScreen(screen);document.body.classList.toggle('focus-mode',focused);const pageContent=variant==='m'?espadaPage():['l','m'].includes(variant)?referencePage():variant==='j'?duoPage():variant==='i'?clarityPage():isExperiment()?experimentPage():variant==='e'?simplePage():variant==='d'?discoveryPage():({today,learn,lesson,practice,progress:result,profile}[screen])();app.innerHTML=variant==='m'?espadaShell(pageContent,animate):['l','m'].includes(variant)?referenceShell(pageContent,animate):variant==='j'?duoShell(pageContent,animate):variant==='i'?clarityShell(pageContent,animate):focused?focusShell(pageContent,animate):variant==='h'?atlasShell(pageContent,animate):`<div class="shell"><header class="app-header"><button class="brand" data-go="today" aria-label="Espada — главная"><img src="assets/knight-light.jpg" alt="">espada.</button>${nav('top-nav')}<button class="avatar" data-go="profile" aria-label="Профиль Алексея">АМ</button></header><main class="main ${animate?'scene':''}">${pageContent}</main><footer class="app-footer">Учебный прототип · демонстрационные данные</footer>${nav('bottom-nav')}</div>`;mountRadar();mountClarity(animate);if(!animate&&focusKey){const target=app.querySelector(`[data-${focusKey[0]}="${focusKey[1]}"]`);if(target&&!target.disabled)target.focus();else if(focusKey[1]==='check')app.querySelector('[data-action="question-next"]')?.focus();else if(focusKey[1]==='hint')app.querySelector('.answer.selected, .answer, .i-answer.selected, .i-answer, .l-answer.selected, .l-answer')?.focus()}if(screen==='learn'&&!['l','m'].includes(variant)){document.getElementById('search').value=query;document.getElementById('grade').value=grade;document.getElementById('search').oninput=e=>{query=e.target.value;document.getElementById('topics').innerHTML=topicCards()};document.getElementById('grade').onchange=e=>{grade=e.target.value;document.getElementById('topics').innerHTML=topicCards()}}}
function notify(){if(window.parent!==window)window.parent.postMessage({type:'espada-lab-screen',screen},location.protocol==='file:'?'*':location.origin)}
function go(next){if(isLessonScreen(next)&&!isLessonScreen(screen))lessonReturnScreen=screen;screen=next;render();window.scrollTo({top:0,behavior:'instant'});document.getElementById('announcement').textContent=['l','m'].includes(variant)&&screen==='profile'?'Лига':screenNames[screen];notify()}
function resetPractice(){question=0;choice=null;checked=false;hinted=false;attempts=[]}
function chooseTopic(i){if(['l','m'].includes(variant)){referenceSelectTopic(i);return}if(['i','j','l','m'].includes(variant)){clarityChooseTopic(i);return}if(topicIndex!==i){topicIndex=i;part=0;readParts.clear();resetPractice()}go('lesson')}
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.go){go(b.dataset.go);return}if(b.dataset.topic!==undefined){chooseTopic(Number(b.dataset.topic));return}if(b.dataset.part!==undefined){part=Number(b.dataset.part);render();return}if(b.dataset.choice!==undefined){choice=Number(b.dataset.choice);render(false);return}switch(b.dataset.action){case'exit-lesson':go(lessonReturnScreen);break;case'assigned':chooseTopic(0);break;case'part-next':readParts.add(part);if(part<2){part++;render();window.scrollTo({top:0,behavior:'instant'})}else go('practice');break;case'part-back':part=Math.max(0,part-1);render();break;case'hint':hinted=true;render(false);if(['l','m'].includes(variant))app.querySelector('.l-hint')?.scrollIntoView({block:'center',behavior:motion?'smooth':'instant'});break;case'check':if(choice===null||checked)return;checked=true;attempts.push({correct:choice===activeQuestion().correct,hinted,choice});if(['i','j','l','m'].includes(variant)&&choice===activeQuestion().correct)clarityEarned.add(topicIndex+':'+question);render(false);break;case'question-next':if(question===2){go('progress')}else{question++;choice=null;checked=false;hinted=false;render();window.scrollTo({top:0,behavior:'instant'})}break;case'retry':resetPractice();go('practice');break;case'review':go('lesson');break;case'clear-search':query='';grade='all';render(false);break;default:if(screenNames[b.dataset.action])go(b.dataset.action)}});
window.addEventListener('message',e=>{if(e.source!==parent||(location.protocol!=='file:'&&e.origin!==location.origin))return;const d=e.data;if(d?.type==='espada-lab-config'&&['a','b','c','d','e','f','g','h','i','j','l','m'].includes(d.variant)&&screenNames[d.screen]){const change=variant!==d.variant||screen!==d.screen||dark!==d.dark||motion!==d.motion;if(isLessonScreen(d.screen)&&!isLessonScreen(screen))lessonReturnScreen=screen;variant=d.variant;screen=d.screen;dark=!!d.dark;motion=!!d.motion;if(change){render();document.getElementById('announcement').textContent=['l','m'].includes(variant)&&screen==='profile'?'Лига':screenNames[screen];window.scrollTo({top:0,behavior:'instant'})}}if(d?.type==='espada-lab-reset'){referenceReady=false;clarityResetProgress();for(const key of Object.keys(discoveryFactors))delete discoveryFactors[key];part=0;readParts.clear();resetPractice();for(const key of Object.keys(clarityFactors))delete clarityFactors[key];render()}});
const params=new URLSearchParams(location.search);dark=params.get('dark')==='1';motion=params.get('motion')!=='0';if(['a','b','c','d','e','f','g','h','i','j','l','m'].includes(params.get('v')))variant=params.get('v');if(screenNames[params.get('screen')])screen=params.get('screen');if(variant==='l'&&!params.has('dark'))dark=true;render();if(parent!==window)parent.postMessage({type:'espada-lab-ready'},location.protocol==='file:'?'*':location.origin);

document.addEventListener('keydown',event=>{if(event.key==='Escape'&&['d','e','f','g','h','i','j','l','m'].includes(variant)&&isLessonScreen(screen)){event.preventDefault();go(lessonReturnScreen)}});
