// Same six dimensions as src/data/reportPresets.ts; deliberately synthetic reports.
const radarAreas=[
  {label:'Вычисления',lines:['Вычисления'],current:9,previous:7,total:10},
  {label:'Дроби',lines:['Дроби'],current:6,previous:4,total:10},
  {label:'Отношения',lines:['Отношения'],current:8,previous:6,total:10},
  {label:'Уравнения',lines:['Уравнения'],current:7,previous:6,total:10},
  {label:'Геометрия',lines:['Геометрия'],current:9,previous:7,total:10},
  {label:'Данные и шанс',lines:['Данные','и шанс'],current:7,previous:5,total:10},
];
let radarCompare=true,radarSelected=1,radarObserver;
function radarValue(area,period){return Math.round(area[period]/area.total*100)}
function radarDetail(){if(['i','j','l','m'].includes(variant))return clarityRadarDetail();const a=radarAreas[radarSelected],now=radarValue(a,'current'),before=radarValue(a,'previous');return `<span class="d-mini-label">${a.label}</span><div class="d-radar-detail-value"><strong>${now}%</strong><span>${a.current} из ${a.total} верно</span>${radarCompare?`<span class="d-radar-delta">+${now-before} п. п.</span>`:''}</div><p>${radarCompare?`18 сентября: ${a.previous} из ${a.total} · ${before}%.`:'Результат работы от 2 октября.'}</p>`}
function discoveryRadar(){return `<section class="d-radar-section" aria-labelledby="radar-title"><div class="d-radar-heading"><div><span class="d-mini-label">РАБОТЫ УЧИТЕЛЯ · УЧЕБНЫЙ ПРИМЕР</span><h2 id="radar-title">Твоя карта результатов</h2><p>Математика · шесть направлений · 2 октября</p></div><label class="d-compare-control"><input id="radar-compare" type="checkbox" ${radarCompare?'checked':''}><span>Сравнить с прошлой</span></label></div><div class="d-radar-layout"><div class="d-radar-figure"><div id="radar-drawing"></div><div class="d-radar-legend"><span><i class="current"></i>2 октября</span><span class="d-previous-legend" ${radarCompare?'':'hidden'}><i class="previous"></i>18 сентября</span></div></div><div class="d-radar-summary"><div id="radar-detail" class="d-radar-detail" aria-live="polite">${radarDetail()}</div><div class="d-radar-area-list" aria-label="Разделы работы">${radarAreas.map((a,i)=>`<button data-radar-area="${i}" aria-pressed="${i===radarSelected}"><span>${a.label}</span><span><b>${a.current}</b> / ${a.total}</span><span class="d-area-percent">${radarValue(a,'current')}%</span></button>`).join('')}</div></div></div><div class="d-radar-footnote"><span>Шкала 0–100% · доля правильных ответов</span><span>Демо-данные · практика ниже считается отдельно</span></div></section>`}
function paintRadar(){if(['i','j','l','m'].includes(variant)){paintClarityRadar();return}const target=document.getElementById('radar-drawing');if(!target)return;const width=Math.max(240,target.getBoundingClientRect().width),r=Math.min(112,width*.235),height=2*r+130,cx=width/2,cy=r+59;
  const point=(i,v,extra=0)=>{const angle=i*Math.PI/3-Math.PI/2,dist=r*v/100+extra;return [cx+Math.cos(angle)*dist,cy+Math.sin(angle)*dist]};
  const points=v=>radarAreas.map((_,i)=>point(i,v).join(',')).join(' ');
  const polygon=period=>radarAreas.map((a,i)=>point(i,radarValue(a,period)).join(',')).join(' ');
  const description=radarAreas.map(a=>`${a.label}: ${a.current} из ${a.total}, ${radarValue(a,'current')}%${radarCompare?`; раньше ${a.previous} из ${a.total}, ${radarValue(a,'previous')}%`:''}`).join('. ');
  target.innerHTML=`<svg class="d-radar-svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-labelledby="radar-svg-title radar-svg-desc"><title id="radar-svg-title">Радар результатов по шести разделам</title><desc id="radar-svg-desc">${description}. Фиксированная шкала от 0 до 100 процентов.</desc>${[25,50,75,100].map(v=>`<polygon class="d-radar-grid" points="${points(v)}"/>`).join('')}${radarAreas.map((a,i)=>{const[x,y]=point(i,100),[tx,ty]=point(i,100,32);return `<line class="d-radar-grid" x1="${cx}" y1="${cy}" x2="${x}" y2="${y}"/><text class="d-radar-label" x="${tx}" y="${ty-5-(a.lines.length-1)*6}" text-anchor="middle">${a.lines.map((line,j)=>`<tspan x="${tx}" dy="${j?12:0}">${line}</tspan>`).join('')}<tspan x="${tx}" dy="17" class="d-radar-label-value">${radarValue(a,'current')}%</tspan></text>`}).join('')}<g class="d-radar-previous ${radarCompare?'':'is-hidden'}"><polygon points="${polygon('previous')}"/>${radarAreas.map((a,i)=>{const[x,y]=point(i,radarValue(a,'previous'));return `<circle cx="${x}" cy="${y}" r="3"/>`}).join('')}</g><polygon class="d-radar-current" points="${polygon('current')}"/>${radarAreas.map((a,i)=>{const[x,y]=point(i,radarValue(a,'current'));return `<g class="d-radar-point ${radarSelected===i?'selected':''}" data-radar-area="${i}"><title>${a.label}: ${a.current} из ${a.total}</title><circle class="d-radar-hit" cx="${x}" cy="${y}" r="17"/><circle class="d-radar-halo" cx="${x}" cy="${y}" r="9"/><circle class="d-radar-dot" cx="${x}" cy="${y}" r="4"/></g>`}).join('')}<text class="d-radar-scale" x="${cx+6}" y="${cy+12}">0</text><text class="d-radar-scale" x="${cx+6}" y="${cy-r+13}">100%</text></svg>`;
}
function mountRadar(){radarObserver?.disconnect();radarObserver=null;const target=document.getElementById('radar-drawing');if(!target)return;paintRadar();radarObserver=new ResizeObserver(paintRadar);radarObserver.observe(target)}
document.addEventListener('click',event=>{const area=event.target.closest('[data-radar-area]');if(!area)return;radarSelected=Number(area.dataset.radarArea);document.querySelectorAll('.d-radar-area-list button').forEach((b,i)=>b.setAttribute('aria-pressed',i===radarSelected));document.getElementById('radar-detail').innerHTML=radarDetail();paintRadar()});
document.addEventListener('change',event=>{if(event.target.id!=='radar-compare')return;radarCompare=event.target.checked;document.querySelector('.d-previous-legend').hidden=!radarCompare;document.getElementById('radar-detail').innerHTML=radarDetail();paintRadar()});
